name: Release

on:
  push:
    branches:
      - master
      - next
      - rc
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release / Node 18

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install deps
        run: npm clean-install

      - name: Run tests
        run: npm run test:coverage

      - name: Build package
        run: npm run build

      - name: Create a release
        run: npx semantic-release@^18.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
